### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by warrenvw** [StackStorm/st2-docker#22]
Please do not modify this entry as it will be overwritten. I am maintaining markup in a separate file. Leave a new comment with any suggestions.

# Objective

To provide an official Docker-based solution for StackStorm. It may be used for evaluation, pack development, and light production. Long term, we expect to provide a Docker-based solution that makes it easy to scale and build a highly available system that can be used in production.
 
# Roadmap

We welcome you to submit issues and PR's. We expect the roadmap to change as new requests are submitted. The following short and long term tasks and goals have been identified.

## Short term

Besides the known [issues](https://github.com/StackStorm/st2-docker/issues), we plan to complete the following within the next couple weeks:

 - [ ] Investigate supporting Docker Stack in addition to Docker Compose.
 - [ ] Remove `VOLUME` instruction in current `Dockerfile`. Update `README.md` with instructions on how to change `docker-compose.yml`, or do similar via CLI.
 - [x] Remove [Dockerfile#L74](https://github.com/StackStorm/st2-docker/blob/master/images/stackstorm/Dockerfile#L74) and add `/entrypoint.d` like this: [entrypoint.sh#L60-L67](https://github.com/shusugmt/docker-st2/blob/master/entrypoint.sh#L60-L67). Update `README.md` with instructions on how to modify `pack_base_path`.

## Long term

These are features or tasks we expect to work on in the future. As we begin work, they will be moved to the "Short term" section.

 - [ ] Create an image that supports running one app per container (see [docker-compose.yml](https://gitlab.com/smithx10/st2/blob/master/docker-compose.yml)). This makes it easy to scale, and build a highly available system.
    - Heed [12 Fractured Apps](https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c), [Twelve-Factor App: Logs](https://12factor.net/logs) and [Twelve-Factor App: Concurrency](https://12factor.net/concurrency)
    - Identify any possible required changes to `st2` repo.
 - [ ] Support for K8S.
 - [ ] Support for Swarm.
 - [ ] Support for Consul.

**Comment by johnarnold** [comment]
IMO, don't get too wrapped up in container orchestration, as there are many competing solutions, and anybody with that level of sophistication can probably integrate it themselves. That's a second order optimization.

Start with getting the Images really ironed out, get the docs really solid and have one good example of how to deploy (e.g. Docker-compose), including best practices on how to pull in packs, configs and SSL certs, how to do upgrades.
Make a list of what is required to move from "eval, light production" to "full production, scale out" for transparency and so others can help out.

**Comment by shreyas-shinde** [comment]
any plan for supporting st2chatops 1ppc?
